//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertTheString.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tblEmployee
    {
        [DisplayName("Employee ID")]
        public int Id { get; set; }

        [DisplayName("First Name")]
        public string firstname { get; set; }

        [DisplayName("Last Name")]
        public string lastname { get; set; }

        [DisplayName("Employee Type")]
        public int employeeType { get; set; }
    
        public virtual tblLocation tblLocation { get; set; }
    }
}
